package clases;
// Generated 26-dic-2014 9:42:29 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {

	private static final long serialVersionUID=1L;
     private int id;
     private String descripcion;
     private Integer stockactual;
     private Integer stockminimo;
     private Integer pvp;
     private Set<Ventas> ventases = new HashSet<Ventas>(0);

    public Productos() {
    }

	
    public Productos(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public Productos(int id, String descripcion, Integer stockactual, Integer stockminimo, Integer pvp, Set<Ventas> ventases) {
       this.id = id;
       this.descripcion = descripcion;
       this.stockactual = stockactual;
       this.stockminimo = stockminimo;
       this.pvp = pvp;
       this.ventases = ventases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getStockactual() {
        return this.stockactual;
    }
    
    public void setStockactual(Integer stockactual) {
        this.stockactual = stockactual;
    }
    public Integer getStockminimo() {
        return this.stockminimo;
    }
    
    public void setStockminimo(Integer stockminimo) {
        this.stockminimo = stockminimo;
    }
    public Integer getPvp() {
        return this.pvp;
    }
    
    public void setPvp(Integer pvp) {
        this.pvp = pvp;
    }
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }




}


